spring:
  profiles:
    active: local
  kafka:
    bootstrap-servers: 127.0.0.1:9092



# Topic
kafka.topic:
    publisher:
      integrationDataFpKeluaran: fpkeluaran
      integrationDataFpKeluaranPembatalan: fpkeluaran-pembatalan
      integrationDataFpMasukan: fpmasukan
      integrationDataFpMasukanPembatalan: fpmasukan-pembatalan
      integrationDataDocDipersamakanPk: docdipersamakan-pk
      integrationDataDocDipersamakanPkPembatalan: docdipersamakan-pk-pembatalan
      integrationDataDocDipersamakanPm: docdipersamakan-pm
      integrationDataDocDipersamakanPmPembatalan: docdipersamakan-pm-pembatalan
